// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cabrera.planes;

import com.cabrera.planes.Carrera;
import com.cabrera.planes.CarreraDataOnDemand;
import com.cabrera.planes.NivelDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CarreraDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CarreraDataOnDemand: @Component;
    
    private Random CarreraDataOnDemand.rnd = new SecureRandom();
    
    private List<Carrera> CarreraDataOnDemand.data;
    
    @Autowired
    NivelDataOnDemand CarreraDataOnDemand.nivelDataOnDemand;
    
    public Carrera CarreraDataOnDemand.getNewTransientCarrera(int index) {
        Carrera obj = new Carrera();
        setCodigo(obj, index);
        setNombre(obj, index);
        return obj;
    }
    
    public void CarreraDataOnDemand.setCodigo(Carrera obj, int index) {
        String codigo = "codigo_" + index;
        if (codigo.length() > 1024) {
            codigo = codigo.substring(0, 1024);
        }
        obj.setCodigo(codigo);
    }
    
    public void CarreraDataOnDemand.setNombre(Carrera obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 64) {
            nombre = nombre.substring(0, 64);
        }
        obj.setNombre(nombre);
    }
    
    public Carrera CarreraDataOnDemand.getSpecificCarrera(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Carrera obj = data.get(index);
        Long id = obj.getId();
        return Carrera.findCarrera(id);
    }
    
    public Carrera CarreraDataOnDemand.getRandomCarrera() {
        init();
        Carrera obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Carrera.findCarrera(id);
    }
    
    public boolean CarreraDataOnDemand.modifyCarrera(Carrera obj) {
        return false;
    }
    
    public void CarreraDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Carrera.findCarreraEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Carrera' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Carrera>();
        for (int i = 0; i < 10; i++) {
            Carrera obj = getNewTransientCarrera(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
