// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cabrera.planes;

import com.cabrera.planes.Carrera;
import com.cabrera.planes.CarreraDataOnDemand;
import com.cabrera.planes.CarreraIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CarreraIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CarreraIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CarreraIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CarreraIntegrationTest: @Transactional;
    
    @Autowired
    CarreraDataOnDemand CarreraIntegrationTest.dod;
    
    @Test
    public void CarreraIntegrationTest.testCountCarreras() {
        Assert.assertNotNull("Data on demand for 'Carrera' failed to initialize correctly", dod.getRandomCarrera());
        long count = Carrera.countCarreras();
        Assert.assertTrue("Counter for 'Carrera' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CarreraIntegrationTest.testFindCarrera() {
        Carrera obj = dod.getRandomCarrera();
        Assert.assertNotNull("Data on demand for 'Carrera' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Carrera' failed to provide an identifier", id);
        obj = Carrera.findCarrera(id);
        Assert.assertNotNull("Find method for 'Carrera' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Carrera' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CarreraIntegrationTest.testFindAllCarreras() {
        Assert.assertNotNull("Data on demand for 'Carrera' failed to initialize correctly", dod.getRandomCarrera());
        long count = Carrera.countCarreras();
        Assert.assertTrue("Too expensive to perform a find all test for 'Carrera', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Carrera> result = Carrera.findAllCarreras();
        Assert.assertNotNull("Find all method for 'Carrera' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Carrera' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CarreraIntegrationTest.testFindCarreraEntries() {
        Assert.assertNotNull("Data on demand for 'Carrera' failed to initialize correctly", dod.getRandomCarrera());
        long count = Carrera.countCarreras();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Carrera> result = Carrera.findCarreraEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Carrera' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Carrera' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CarreraIntegrationTest.testFlush() {
        Carrera obj = dod.getRandomCarrera();
        Assert.assertNotNull("Data on demand for 'Carrera' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Carrera' failed to provide an identifier", id);
        obj = Carrera.findCarrera(id);
        Assert.assertNotNull("Find method for 'Carrera' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCarrera(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Carrera' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CarreraIntegrationTest.testMergeUpdate() {
        Carrera obj = dod.getRandomCarrera();
        Assert.assertNotNull("Data on demand for 'Carrera' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Carrera' failed to provide an identifier", id);
        obj = Carrera.findCarrera(id);
        boolean modified =  dod.modifyCarrera(obj);
        Integer currentVersion = obj.getVersion();
        Carrera merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Carrera' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CarreraIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Carrera' failed to initialize correctly", dod.getRandomCarrera());
        Carrera obj = dod.getNewTransientCarrera(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Carrera' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Carrera' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Carrera' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CarreraIntegrationTest.testRemove() {
        Carrera obj = dod.getRandomCarrera();
        Assert.assertNotNull("Data on demand for 'Carrera' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Carrera' failed to provide an identifier", id);
        obj = Carrera.findCarrera(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Carrera' with identifier '" + id + "'", Carrera.findCarrera(id));
    }
    
}
