// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cabrera.planes;

import com.cabrera.planes.Ciudad;
import com.cabrera.planes.CiudadDataOnDemand;
import com.cabrera.planes.CiudadIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CiudadIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CiudadIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CiudadIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CiudadIntegrationTest: @Transactional;
    
    @Autowired
    CiudadDataOnDemand CiudadIntegrationTest.dod;
    
    @Test
    public void CiudadIntegrationTest.testCountCiudads() {
        Assert.assertNotNull("Data on demand for 'Ciudad' failed to initialize correctly", dod.getRandomCiudad());
        long count = Ciudad.countCiudads();
        Assert.assertTrue("Counter for 'Ciudad' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CiudadIntegrationTest.testFindCiudad() {
        Ciudad obj = dod.getRandomCiudad();
        Assert.assertNotNull("Data on demand for 'Ciudad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ciudad' failed to provide an identifier", id);
        obj = Ciudad.findCiudad(id);
        Assert.assertNotNull("Find method for 'Ciudad' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Ciudad' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CiudadIntegrationTest.testFindAllCiudads() {
        Assert.assertNotNull("Data on demand for 'Ciudad' failed to initialize correctly", dod.getRandomCiudad());
        long count = Ciudad.countCiudads();
        Assert.assertTrue("Too expensive to perform a find all test for 'Ciudad', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Ciudad> result = Ciudad.findAllCiudads();
        Assert.assertNotNull("Find all method for 'Ciudad' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Ciudad' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CiudadIntegrationTest.testFindCiudadEntries() {
        Assert.assertNotNull("Data on demand for 'Ciudad' failed to initialize correctly", dod.getRandomCiudad());
        long count = Ciudad.countCiudads();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Ciudad> result = Ciudad.findCiudadEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Ciudad' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Ciudad' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CiudadIntegrationTest.testFlush() {
        Ciudad obj = dod.getRandomCiudad();
        Assert.assertNotNull("Data on demand for 'Ciudad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ciudad' failed to provide an identifier", id);
        obj = Ciudad.findCiudad(id);
        Assert.assertNotNull("Find method for 'Ciudad' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCiudad(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Ciudad' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CiudadIntegrationTest.testMergeUpdate() {
        Ciudad obj = dod.getRandomCiudad();
        Assert.assertNotNull("Data on demand for 'Ciudad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ciudad' failed to provide an identifier", id);
        obj = Ciudad.findCiudad(id);
        boolean modified =  dod.modifyCiudad(obj);
        Integer currentVersion = obj.getVersion();
        Ciudad merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Ciudad' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CiudadIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Ciudad' failed to initialize correctly", dod.getRandomCiudad());
        Ciudad obj = dod.getNewTransientCiudad(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Ciudad' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Ciudad' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Ciudad' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CiudadIntegrationTest.testRemove() {
        Ciudad obj = dod.getRandomCiudad();
        Assert.assertNotNull("Data on demand for 'Ciudad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ciudad' failed to provide an identifier", id);
        obj = Ciudad.findCiudad(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Ciudad' with identifier '" + id + "'", Ciudad.findCiudad(id));
    }
    
}
