// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cabrera.planes;

import com.cabrera.planes.EstadoMateria;
import com.cabrera.planes.EstadoMateriaDataOnDemand;
import com.cabrera.planes.EstadoMateriaIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EstadoMateriaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EstadoMateriaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EstadoMateriaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EstadoMateriaIntegrationTest: @Transactional;
    
    @Autowired
    EstadoMateriaDataOnDemand EstadoMateriaIntegrationTest.dod;
    
    @Test
    public void EstadoMateriaIntegrationTest.testCountEstadoMaterias() {
        Assert.assertNotNull("Data on demand for 'EstadoMateria' failed to initialize correctly", dod.getRandomEstadoMateria());
        long count = EstadoMateria.countEstadoMaterias();
        Assert.assertTrue("Counter for 'EstadoMateria' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EstadoMateriaIntegrationTest.testFindEstadoMateria() {
        EstadoMateria obj = dod.getRandomEstadoMateria();
        Assert.assertNotNull("Data on demand for 'EstadoMateria' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EstadoMateria' failed to provide an identifier", id);
        obj = EstadoMateria.findEstadoMateria(id);
        Assert.assertNotNull("Find method for 'EstadoMateria' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EstadoMateria' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EstadoMateriaIntegrationTest.testFindAllEstadoMaterias() {
        Assert.assertNotNull("Data on demand for 'EstadoMateria' failed to initialize correctly", dod.getRandomEstadoMateria());
        long count = EstadoMateria.countEstadoMaterias();
        Assert.assertTrue("Too expensive to perform a find all test for 'EstadoMateria', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EstadoMateria> result = EstadoMateria.findAllEstadoMaterias();
        Assert.assertNotNull("Find all method for 'EstadoMateria' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EstadoMateria' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EstadoMateriaIntegrationTest.testFindEstadoMateriaEntries() {
        Assert.assertNotNull("Data on demand for 'EstadoMateria' failed to initialize correctly", dod.getRandomEstadoMateria());
        long count = EstadoMateria.countEstadoMaterias();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EstadoMateria> result = EstadoMateria.findEstadoMateriaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'EstadoMateria' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EstadoMateria' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EstadoMateriaIntegrationTest.testFlush() {
        EstadoMateria obj = dod.getRandomEstadoMateria();
        Assert.assertNotNull("Data on demand for 'EstadoMateria' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EstadoMateria' failed to provide an identifier", id);
        obj = EstadoMateria.findEstadoMateria(id);
        Assert.assertNotNull("Find method for 'EstadoMateria' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEstadoMateria(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'EstadoMateria' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EstadoMateriaIntegrationTest.testMergeUpdate() {
        EstadoMateria obj = dod.getRandomEstadoMateria();
        Assert.assertNotNull("Data on demand for 'EstadoMateria' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EstadoMateria' failed to provide an identifier", id);
        obj = EstadoMateria.findEstadoMateria(id);
        boolean modified =  dod.modifyEstadoMateria(obj);
        Integer currentVersion = obj.getVersion();
        EstadoMateria merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'EstadoMateria' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EstadoMateriaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'EstadoMateria' failed to initialize correctly", dod.getRandomEstadoMateria());
        EstadoMateria obj = dod.getNewTransientEstadoMateria(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EstadoMateria' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EstadoMateria' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'EstadoMateria' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EstadoMateriaIntegrationTest.testRemove() {
        EstadoMateria obj = dod.getRandomEstadoMateria();
        Assert.assertNotNull("Data on demand for 'EstadoMateria' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EstadoMateria' failed to provide an identifier", id);
        obj = EstadoMateria.findEstadoMateria(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'EstadoMateria' with identifier '" + id + "'", EstadoMateria.findEstadoMateria(id));
    }
    
}
