// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cabrera.planes;

import com.cabrera.planes.Estudiante;
import com.cabrera.planes.EstudianteDataOnDemand;
import com.cabrera.planes.EstudianteIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EstudianteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EstudianteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EstudianteIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EstudianteIntegrationTest: @Transactional;
    
    @Autowired
    EstudianteDataOnDemand EstudianteIntegrationTest.dod;
    
    @Test
    public void EstudianteIntegrationTest.testCountEstudiantes() {
        Assert.assertNotNull("Data on demand for 'Estudiante' failed to initialize correctly", dod.getRandomEstudiante());
        long count = Estudiante.countEstudiantes();
        Assert.assertTrue("Counter for 'Estudiante' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EstudianteIntegrationTest.testFindEstudiante() {
        Estudiante obj = dod.getRandomEstudiante();
        Assert.assertNotNull("Data on demand for 'Estudiante' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Estudiante' failed to provide an identifier", id);
        obj = Estudiante.findEstudiante(id);
        Assert.assertNotNull("Find method for 'Estudiante' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Estudiante' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EstudianteIntegrationTest.testFindAllEstudiantes() {
        Assert.assertNotNull("Data on demand for 'Estudiante' failed to initialize correctly", dod.getRandomEstudiante());
        long count = Estudiante.countEstudiantes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Estudiante', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Estudiante> result = Estudiante.findAllEstudiantes();
        Assert.assertNotNull("Find all method for 'Estudiante' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Estudiante' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EstudianteIntegrationTest.testFindEstudianteEntries() {
        Assert.assertNotNull("Data on demand for 'Estudiante' failed to initialize correctly", dod.getRandomEstudiante());
        long count = Estudiante.countEstudiantes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Estudiante> result = Estudiante.findEstudianteEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Estudiante' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Estudiante' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EstudianteIntegrationTest.testFlush() {
        Estudiante obj = dod.getRandomEstudiante();
        Assert.assertNotNull("Data on demand for 'Estudiante' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Estudiante' failed to provide an identifier", id);
        obj = Estudiante.findEstudiante(id);
        Assert.assertNotNull("Find method for 'Estudiante' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEstudiante(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Estudiante' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EstudianteIntegrationTest.testMergeUpdate() {
        Estudiante obj = dod.getRandomEstudiante();
        Assert.assertNotNull("Data on demand for 'Estudiante' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Estudiante' failed to provide an identifier", id);
        obj = Estudiante.findEstudiante(id);
        boolean modified =  dod.modifyEstudiante(obj);
        Integer currentVersion = obj.getVersion();
        Estudiante merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Estudiante' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EstudianteIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Estudiante' failed to initialize correctly", dod.getRandomEstudiante());
        Estudiante obj = dod.getNewTransientEstudiante(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Estudiante' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Estudiante' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Estudiante' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EstudianteIntegrationTest.testRemove() {
        Estudiante obj = dod.getRandomEstudiante();
        Assert.assertNotNull("Data on demand for 'Estudiante' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Estudiante' failed to provide an identifier", id);
        obj = Estudiante.findEstudiante(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Estudiante' with identifier '" + id + "'", Estudiante.findEstudiante(id));
    }
    
}
