// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cabrera.planes;

import com.cabrera.planes.Materia;
import com.cabrera.planes.MateriaDataOnDemand;
import com.cabrera.planes.MateriaIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MateriaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MateriaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MateriaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MateriaIntegrationTest: @Transactional;
    
    @Autowired
    MateriaDataOnDemand MateriaIntegrationTest.dod;
    
    @Test
    public void MateriaIntegrationTest.testCountMaterias() {
        Assert.assertNotNull("Data on demand for 'Materia' failed to initialize correctly", dod.getRandomMateria());
        long count = Materia.countMaterias();
        Assert.assertTrue("Counter for 'Materia' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MateriaIntegrationTest.testFindMateria() {
        Materia obj = dod.getRandomMateria();
        Assert.assertNotNull("Data on demand for 'Materia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Materia' failed to provide an identifier", id);
        obj = Materia.findMateria(id);
        Assert.assertNotNull("Find method for 'Materia' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Materia' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MateriaIntegrationTest.testFindAllMaterias() {
        Assert.assertNotNull("Data on demand for 'Materia' failed to initialize correctly", dod.getRandomMateria());
        long count = Materia.countMaterias();
        Assert.assertTrue("Too expensive to perform a find all test for 'Materia', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Materia> result = Materia.findAllMaterias();
        Assert.assertNotNull("Find all method for 'Materia' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Materia' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MateriaIntegrationTest.testFindMateriaEntries() {
        Assert.assertNotNull("Data on demand for 'Materia' failed to initialize correctly", dod.getRandomMateria());
        long count = Materia.countMaterias();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Materia> result = Materia.findMateriaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Materia' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Materia' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MateriaIntegrationTest.testFlush() {
        Materia obj = dod.getRandomMateria();
        Assert.assertNotNull("Data on demand for 'Materia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Materia' failed to provide an identifier", id);
        obj = Materia.findMateria(id);
        Assert.assertNotNull("Find method for 'Materia' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMateria(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Materia' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MateriaIntegrationTest.testMergeUpdate() {
        Materia obj = dod.getRandomMateria();
        Assert.assertNotNull("Data on demand for 'Materia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Materia' failed to provide an identifier", id);
        obj = Materia.findMateria(id);
        boolean modified =  dod.modifyMateria(obj);
        Integer currentVersion = obj.getVersion();
        Materia merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Materia' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MateriaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Materia' failed to initialize correctly", dod.getRandomMateria());
        Materia obj = dod.getNewTransientMateria(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Materia' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Materia' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Materia' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MateriaIntegrationTest.testRemove() {
        Materia obj = dod.getRandomMateria();
        Assert.assertNotNull("Data on demand for 'Materia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Materia' failed to provide an identifier", id);
        obj = Materia.findMateria(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Materia' with identifier '" + id + "'", Materia.findMateria(id));
    }
    
}
