// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cabrera.planes;

import com.cabrera.planes.Materia;
import com.cabrera.planes.MateriaDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect MateriaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MateriaDataOnDemand: @Component;
    
    private Random MateriaDataOnDemand.rnd = new SecureRandom();
    
    private List<Materia> MateriaDataOnDemand.data;
    
    public Materia MateriaDataOnDemand.getNewTransientMateria(int index) {
        Materia obj = new Materia();
        setCodigo(obj, index);
        setNombre(obj, index);
        return obj;
    }
    
    public void MateriaDataOnDemand.setCodigo(Materia obj, int index) {
        String codigo = "codigo_" + index;
        if (codigo.length() > 64) {
            codigo = codigo.substring(0, 64);
        }
        obj.setCodigo(codigo);
    }
    
    public void MateriaDataOnDemand.setNombre(Materia obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 64) {
            nombre = nombre.substring(0, 64);
        }
        obj.setNombre(nombre);
    }
    
    public Materia MateriaDataOnDemand.getSpecificMateria(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Materia obj = data.get(index);
        Long id = obj.getId();
        return Materia.findMateria(id);
    }
    
    public Materia MateriaDataOnDemand.getRandomMateria() {
        init();
        Materia obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Materia.findMateria(id);
    }
    
    public boolean MateriaDataOnDemand.modifyMateria(Materia obj) {
        return false;
    }
    
    public void MateriaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Materia.findMateriaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Materia' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Materia>();
        for (int i = 0; i < 10; i++) {
            Materia obj = getNewTransientMateria(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
