// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cabrera.planes;

import com.cabrera.planes.Nivel;
import com.cabrera.planes.NivelDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect NivelDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NivelDataOnDemand: @Component;
    
    private Random NivelDataOnDemand.rnd = new SecureRandom();
    
    private List<Nivel> NivelDataOnDemand.data;
    
    public Nivel NivelDataOnDemand.getNewTransientNivel(int index) {
        Nivel obj = new Nivel();
        setNombre(obj, index);
        return obj;
    }
    
    public void NivelDataOnDemand.setNombre(Nivel obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 64) {
            nombre = nombre.substring(0, 64);
        }
        obj.setNombre(nombre);
    }
    
    public Nivel NivelDataOnDemand.getSpecificNivel(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Nivel obj = data.get(index);
        Long id = obj.getId();
        return Nivel.findNivel(id);
    }
    
    public Nivel NivelDataOnDemand.getRandomNivel() {
        init();
        Nivel obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Nivel.findNivel(id);
    }
    
    public boolean NivelDataOnDemand.modifyNivel(Nivel obj) {
        return false;
    }
    
    public void NivelDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Nivel.findNivelEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Nivel' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Nivel>();
        for (int i = 0; i < 10; i++) {
            Nivel obj = getNewTransientNivel(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
