// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cabrera.planes;

import com.cabrera.planes.PlanDeEstudio;
import com.cabrera.planes.PlanDeEstudioDataOnDemand;
import com.cabrera.planes.PlanDeEstudioIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PlanDeEstudioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PlanDeEstudioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PlanDeEstudioIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PlanDeEstudioIntegrationTest: @Transactional;
    
    @Autowired
    PlanDeEstudioDataOnDemand PlanDeEstudioIntegrationTest.dod;
    
    @Test
    public void PlanDeEstudioIntegrationTest.testCountPlanDeEstudios() {
        Assert.assertNotNull("Data on demand for 'PlanDeEstudio' failed to initialize correctly", dod.getRandomPlanDeEstudio());
        long count = PlanDeEstudio.countPlanDeEstudios();
        Assert.assertTrue("Counter for 'PlanDeEstudio' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PlanDeEstudioIntegrationTest.testFindPlanDeEstudio() {
        PlanDeEstudio obj = dod.getRandomPlanDeEstudio();
        Assert.assertNotNull("Data on demand for 'PlanDeEstudio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PlanDeEstudio' failed to provide an identifier", id);
        obj = PlanDeEstudio.findPlanDeEstudio(id);
        Assert.assertNotNull("Find method for 'PlanDeEstudio' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PlanDeEstudio' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PlanDeEstudioIntegrationTest.testFindAllPlanDeEstudios() {
        Assert.assertNotNull("Data on demand for 'PlanDeEstudio' failed to initialize correctly", dod.getRandomPlanDeEstudio());
        long count = PlanDeEstudio.countPlanDeEstudios();
        Assert.assertTrue("Too expensive to perform a find all test for 'PlanDeEstudio', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PlanDeEstudio> result = PlanDeEstudio.findAllPlanDeEstudios();
        Assert.assertNotNull("Find all method for 'PlanDeEstudio' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PlanDeEstudio' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PlanDeEstudioIntegrationTest.testFindPlanDeEstudioEntries() {
        Assert.assertNotNull("Data on demand for 'PlanDeEstudio' failed to initialize correctly", dod.getRandomPlanDeEstudio());
        long count = PlanDeEstudio.countPlanDeEstudios();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PlanDeEstudio> result = PlanDeEstudio.findPlanDeEstudioEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PlanDeEstudio' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PlanDeEstudio' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PlanDeEstudioIntegrationTest.testFlush() {
        PlanDeEstudio obj = dod.getRandomPlanDeEstudio();
        Assert.assertNotNull("Data on demand for 'PlanDeEstudio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PlanDeEstudio' failed to provide an identifier", id);
        obj = PlanDeEstudio.findPlanDeEstudio(id);
        Assert.assertNotNull("Find method for 'PlanDeEstudio' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPlanDeEstudio(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PlanDeEstudio' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PlanDeEstudioIntegrationTest.testMergeUpdate() {
        PlanDeEstudio obj = dod.getRandomPlanDeEstudio();
        Assert.assertNotNull("Data on demand for 'PlanDeEstudio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PlanDeEstudio' failed to provide an identifier", id);
        obj = PlanDeEstudio.findPlanDeEstudio(id);
        boolean modified =  dod.modifyPlanDeEstudio(obj);
        Integer currentVersion = obj.getVersion();
        PlanDeEstudio merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PlanDeEstudio' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PlanDeEstudioIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PlanDeEstudio' failed to initialize correctly", dod.getRandomPlanDeEstudio());
        PlanDeEstudio obj = dod.getNewTransientPlanDeEstudio(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PlanDeEstudio' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PlanDeEstudio' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PlanDeEstudio' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PlanDeEstudioIntegrationTest.testRemove() {
        PlanDeEstudio obj = dod.getRandomPlanDeEstudio();
        Assert.assertNotNull("Data on demand for 'PlanDeEstudio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PlanDeEstudio' failed to provide an identifier", id);
        obj = PlanDeEstudio.findPlanDeEstudio(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PlanDeEstudio' with identifier '" + id + "'", PlanDeEstudio.findPlanDeEstudio(id));
    }
    
}
