// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cabrera.planes;

import com.cabrera.planes.PaisDataOnDemand;
import com.cabrera.planes.Provincia;
import com.cabrera.planes.ProvinciaDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProvinciaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProvinciaDataOnDemand: @Component;
    
    private Random ProvinciaDataOnDemand.rnd = new SecureRandom();
    
    private List<Provincia> ProvinciaDataOnDemand.data;
    
    @Autowired
    PaisDataOnDemand ProvinciaDataOnDemand.paisDataOnDemand;
    
    public Provincia ProvinciaDataOnDemand.getNewTransientProvincia(int index) {
        Provincia obj = new Provincia();
        setCodigo(obj, index);
        setNombre(obj, index);
        return obj;
    }
    
    public void ProvinciaDataOnDemand.setCodigo(Provincia obj, int index) {
        String codigo = "codigo_" + index;
        if (codigo.length() > 1024) {
            codigo = codigo.substring(0, 1024);
        }
        obj.setCodigo(codigo);
    }
    
    public void ProvinciaDataOnDemand.setNombre(Provincia obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 64) {
            nombre = nombre.substring(0, 64);
        }
        obj.setNombre(nombre);
    }
    
    public Provincia ProvinciaDataOnDemand.getSpecificProvincia(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Provincia obj = data.get(index);
        Long id = obj.getId();
        return Provincia.findProvincia(id);
    }
    
    public Provincia ProvinciaDataOnDemand.getRandomProvincia() {
        init();
        Provincia obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Provincia.findProvincia(id);
    }
    
    public boolean ProvinciaDataOnDemand.modifyProvincia(Provincia obj) {
        return false;
    }
    
    public void ProvinciaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Provincia.findProvinciaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Provincia' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Provincia>();
        for (int i = 0; i < 10; i++) {
            Provincia obj = getNewTransientProvincia(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
