// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cabrera.planes;

import com.cabrera.planes.CiudadDataOnDemand;
import com.cabrera.planes.Universidad;
import com.cabrera.planes.UniversidadDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect UniversidadDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UniversidadDataOnDemand: @Component;
    
    private Random UniversidadDataOnDemand.rnd = new SecureRandom();
    
    private List<Universidad> UniversidadDataOnDemand.data;
    
    @Autowired
    CiudadDataOnDemand UniversidadDataOnDemand.ciudadDataOnDemand;
    
    public Universidad UniversidadDataOnDemand.getNewTransientUniversidad(int index) {
        Universidad obj = new Universidad();
        setCodigo(obj, index);
        setNombre(obj, index);
        return obj;
    }
    
    public void UniversidadDataOnDemand.setCodigo(Universidad obj, int index) {
        String codigo = "codigo_" + index;
        if (codigo.length() > 1024) {
            codigo = codigo.substring(0, 1024);
        }
        obj.setCodigo(codigo);
    }
    
    public void UniversidadDataOnDemand.setNombre(Universidad obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 64) {
            nombre = nombre.substring(0, 64);
        }
        obj.setNombre(nombre);
    }
    
    public Universidad UniversidadDataOnDemand.getSpecificUniversidad(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Universidad obj = data.get(index);
        Long id = obj.getId();
        return Universidad.findUniversidad(id);
    }
    
    public Universidad UniversidadDataOnDemand.getRandomUniversidad() {
        init();
        Universidad obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Universidad.findUniversidad(id);
    }
    
    public boolean UniversidadDataOnDemand.modifyUniversidad(Universidad obj) {
        return false;
    }
    
    public void UniversidadDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Universidad.findUniversidadEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Universidad' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Universidad>();
        for (int i = 0; i < 10; i++) {
            Universidad obj = getNewTransientUniversidad(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
