// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cabrera.planes;

import com.cabrera.planes.Universidad;
import com.cabrera.planes.UniversidadDataOnDemand;
import com.cabrera.planes.UniversidadIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UniversidadIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UniversidadIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UniversidadIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UniversidadIntegrationTest: @Transactional;
    
    @Autowired
    UniversidadDataOnDemand UniversidadIntegrationTest.dod;
    
    @Test
    public void UniversidadIntegrationTest.testCountUniversidads() {
        Assert.assertNotNull("Data on demand for 'Universidad' failed to initialize correctly", dod.getRandomUniversidad());
        long count = Universidad.countUniversidads();
        Assert.assertTrue("Counter for 'Universidad' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UniversidadIntegrationTest.testFindUniversidad() {
        Universidad obj = dod.getRandomUniversidad();
        Assert.assertNotNull("Data on demand for 'Universidad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Universidad' failed to provide an identifier", id);
        obj = Universidad.findUniversidad(id);
        Assert.assertNotNull("Find method for 'Universidad' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Universidad' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UniversidadIntegrationTest.testFindAllUniversidads() {
        Assert.assertNotNull("Data on demand for 'Universidad' failed to initialize correctly", dod.getRandomUniversidad());
        long count = Universidad.countUniversidads();
        Assert.assertTrue("Too expensive to perform a find all test for 'Universidad', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Universidad> result = Universidad.findAllUniversidads();
        Assert.assertNotNull("Find all method for 'Universidad' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Universidad' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UniversidadIntegrationTest.testFindUniversidadEntries() {
        Assert.assertNotNull("Data on demand for 'Universidad' failed to initialize correctly", dod.getRandomUniversidad());
        long count = Universidad.countUniversidads();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Universidad> result = Universidad.findUniversidadEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Universidad' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Universidad' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UniversidadIntegrationTest.testFlush() {
        Universidad obj = dod.getRandomUniversidad();
        Assert.assertNotNull("Data on demand for 'Universidad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Universidad' failed to provide an identifier", id);
        obj = Universidad.findUniversidad(id);
        Assert.assertNotNull("Find method for 'Universidad' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUniversidad(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Universidad' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UniversidadIntegrationTest.testMergeUpdate() {
        Universidad obj = dod.getRandomUniversidad();
        Assert.assertNotNull("Data on demand for 'Universidad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Universidad' failed to provide an identifier", id);
        obj = Universidad.findUniversidad(id);
        boolean modified =  dod.modifyUniversidad(obj);
        Integer currentVersion = obj.getVersion();
        Universidad merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Universidad' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UniversidadIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Universidad' failed to initialize correctly", dod.getRandomUniversidad());
        Universidad obj = dod.getNewTransientUniversidad(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Universidad' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Universidad' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Universidad' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UniversidadIntegrationTest.testRemove() {
        Universidad obj = dod.getRandomUniversidad();
        Assert.assertNotNull("Data on demand for 'Universidad' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Universidad' failed to provide an identifier", id);
        obj = Universidad.findUniversidad(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Universidad' with identifier '" + id + "'", Universidad.findUniversidad(id));
    }
    
}
