// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.cabrera.planes;

import com.cabrera.planes.Nivel;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Nivel_Roo_Configurable {
    
    declare @type: Nivel: @Configurable;
    
}
